# Site settings

name:  Hongliang Chi (Frank)

# Short bio or description (displayed in the header)
description: Ph.D. student of Computer Science at Rensselaer Polytechnic Institute (RPI)

avatar: https://raw.githubusercontent.com/frankhlchi/frankhlchi.github.io/master/images/bio.jpeg

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Personal Information
linkedin_url: https://www.linkedin.com/in/frank-hongliang-chi/
github_url: https://github.com/frankhlchi
google_scholar_url: https://scholar.google.com/citations?user=Q8S5vXsAAAAJ&hl=en

# Publications
publications:
  - title: "Active Learning for Graphs with Noisy Structures."
    authors: "Hongliang Chi, Cong Qi, Suhang Wang, Yao Ma"
    link: https://www.mlgworkshop.org/2023/papers/MLG__KDD_2023_paper_9.pdf
    conference: "SDM 2024"
  - title: "Enhancing Graph Contrastive Learning with Node Similarity."
    authors: "Hongliang Chi, Yao Ma"
    link: https://arxiv.org/abs/2208.06743
    status: "arXiv preprint arXiv: 2208.06743, 2022"

# Symposiums and Workshops
symposiums:
  - title: "Active Learning for Graphs with Noisy Structures."
    event: "19th International Workshop on Mining and Learning with Graphs (MLG)"
    year: 2023
    link: https://www.mlgworkshop.org/2023/
  - title: "Enhancing Graph Contrastive Learning with Node Similarity."
    event: "International Conference on Data Mining (SDM) Doctoral Forum, SIAM, Poster"
    year: 2022
    link: https://www.siam.org/conferences/cm/program/special-events/sdm22-special-events

# Awards
awards:
  - name: WSDM 2024 Student Travel Award
  - name: WSDM 2022 Student Travel Award
  - name: SDM 2022 Travel Award

# Services
services:
  - title: "Reviewer"
    organization: "ACM Transactions on Knowledge Discovery from Data (TKDD)"
    year: 2023
  - title: "External Reviewer"
    organization: "The Conference on Information and Knowledge Management (CIKM)"
    year: 2022
  - title: "Reviewer"
    organization: "Machine Learning on Graphs Workshop at WSDM"
    year: 2022
  - title: "External Reviewer"
    organization: "Special Interest Group on Knowledge Discovery and Data Mining (SIGKDD)"
    year: 2022
  - title: "External Reviewer"
    organization: "The Web Conference (WWW)"
    year: 2022

# Volunteering
volunteering:
  - project: 2022 ACM SIGKDD
    location: Washington DC, U.S.
    year: 2022
  - project: "Cornell Course Roster Scheduling under COVID-19 Emergency"
    year: 2020
    details: >-
      Member of Cornell’s Roster Team, implemented a MIP model for room scheduling and assignment under COVID-19 capacity constraints. Related news: [Engineering Behind Cornell's Fall 2020 Schedule](https://www.engineering.cornell.edu/spotlights/unsung-engineering-behind-cornells-fall-2020-schedule).


#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
